spring:
  data:
    mongodb:
      uri: mongodb+srv://springuser:journal_123@cluster0.ite0erw.mongodb.net/?journaldb=Cluster0
      database: journaldb
      auto-index-creation: true


server:
    port: 8081
    servlet:
      context-path: /journal